/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hosp;

import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JSeparator;
import javax.swing.JTextField;

import java.rmi.*;
import java.net.*;
import java.io.Serializable;

/**
 *
 * @author Andrés
 */
public class InterfazCliente extends javax.swing.JFrame implements Serializable {

    static ArrayList<javax.swing.JTextField> tf = new ArrayList<>();

    public InterfazCliente() {
        initComponents();
        tf.add(jTextField1);
        tf.add(jTextField2);
        tf.add(jTextField3);
        tf.add(jTextField4);
        tf.add(jTextField5);
        tf.add(jTextField6);
        tf.add(jTextField7);
        tf.add(jTextField8);
        tf.add(jTextField9);
        tf.add(jTextField10);
        tf.add(jTextField11);
        tf.add(jTextField12);
        tf.add(jTextField13);
        tf.add(jTextField14);
        tf.add(jTextField15);
        tf.add(jTextField16);
        tf.add(jTextField17);
        tf.add(jTextField18);
        tf.add(jTextField19);
        tf.add(jTextField20);
        tf.add(jTextField21);
        tf.add(jTextField22);
        tf.add(jTextField23);
        tf.add(jTextField24);
        tf.add(jTextField25);
        tf.add(jTextField26);
        tf.add(jTextField27);
        tf.add(jTextField28);
        tf.add(jTextField29);
        tf.add(jTextField30);
        tf.add(jTextField31);
        tf.add(jTextField32);
        tf.add(jTextField33);
        tf.add(jTextField34);
        tf.add(jTextField35);
        tf.add(jTextField36);
        System.out.println(tf.size());
        System.out.println(tf);
        tf.forEach(j -> {
            j.setText("");
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jTextField28 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jTextField29 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jTextField30 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jTextField31 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jTextField32 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jTextField33 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jTextField34 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jTextField35 = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jTextField36 = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jTextField27 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        jTextField26 = new javax.swing.JTextField();
        jTextField25 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("SALA DE OBSERVACIÓN");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, -1, -1));

        jLabel8.setText("Puesto 1");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 33, -1, -1));

        jLabel9.setText("Puesto 2");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 33, -1, -1));

        jLabel10.setText("Puesto 3");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 33, -1, -1));

        jLabel11.setText("Puesto 4");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 33, -1, -1));

        jLabel12.setText("Puesto 5");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 33, -1, -1));

        jLabel13.setText("Puesto 6");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 33, -1, -1));

        jLabel14.setText("Puesto 7");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, -1, -1));

        jLabel15.setText("Puesto 8");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, -1, -1));

        jLabel16.setText("Puesto 9");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 30, -1, -1));

        jLabel17.setText("Puesto 10");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 30, -1, -1));

        jLabel32.setText("Puesto 11");
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 79, -1, -1));

        jTextField28.setText("jTextField5");
        jPanel1.add(jTextField28, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 99, 75, -1));

        jLabel33.setText("Puesto 12");
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 79, -1, -1));

        jTextField29.setText("jTextField6");
        jPanel1.add(jTextField29, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 99, 75, -1));

        jLabel34.setText("Puesto 13");
        jPanel1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 79, -1, -1));

        jTextField30.setText("jTextField7");
        jPanel1.add(jTextField30, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 99, 75, -1));

        jLabel35.setText("Puesto 14");
        jPanel1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 79, -1, -1));

        jTextField31.setText("jTextField8");
        jPanel1.add(jTextField31, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 99, 75, -1));

        jLabel36.setText("Puesto 15");
        jPanel1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 79, -1, -1));

        jTextField32.setText("jTextField9");
        jPanel1.add(jTextField32, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 99, 75, -1));

        jLabel37.setText("Puesto 16");
        jPanel1.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 79, -1, -1));

        jTextField33.setText("jTextField10");
        jPanel1.add(jTextField33, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 99, 83, -1));

        jLabel38.setText("Puesto 17");
        jPanel1.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, -1, -1));

        jTextField34.setText("jTextField11");
        jPanel1.add(jTextField34, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, -1, -1));

        jLabel39.setText("Puesto 18");
        jPanel1.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 80, -1, -1));

        jTextField35.setText("jTextField12");
        jPanel1.add(jTextField35, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 100, 75, -1));

        jLabel40.setText("Puesto 19");
        jPanel1.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 80, -1, -1));

        jTextField36.setText("jTextField16");
        jPanel1.add(jTextField36, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 100, -1, -1));

        jLabel41.setText("Puesto 20");
        jPanel1.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 80, -1, -1));

        jTextField27.setText("jTextField13");
        jPanel1.add(jTextField27, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 100, 75, -1));

        jTextField17.setText("jTextField5");
        jPanel1.add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 75, -1));

        jTextField18.setText("jTextField6");
        jPanel1.add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 75, -1));

        jTextField19.setText("jTextField7");
        jPanel1.add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 75, -1));

        jTextField20.setText("jTextField8");
        jPanel1.add(jTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 75, -1));

        jTextField21.setText("jTextField9");
        jPanel1.add(jTextField21, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 75, -1));

        jTextField22.setText("jTextField10");
        jPanel1.add(jTextField22, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 80, -1));

        jTextField23.setText("jTextField11");
        jPanel1.add(jTextField23, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, 70, -1));

        jTextField24.setText("jTextField12");
        jPanel1.add(jTextField24, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 50, 75, -1));

        jTextField26.setText("jTextField16");
        jPanel1.add(jTextField26, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 50, 76, -1));

        jTextField25.setText("jTextField13");
        jPanel1.add(jTextField25, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 50, 75, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 950, 150));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("RECEPCIÓN");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 11, -1, -1));

        jLabel5.setText("Cola de espera");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 31, -1, -1));

        jTextField1.setText("jTextField1");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 51, 389, -1));

        jLabel6.setText("Paciente");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 98, -1, -1));

        jLabel7.setText("Auxiliar");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 98, -1, -1));

        jTextField2.setText("jTextField2");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 118, 102, -1));

        jTextField3.setText("jTextField3");
        jPanel2.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 118, 102, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, 150));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("SALA DE DESCANSO");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 13, -1, -1));

        jTextField4.setText("jTextField4");
        jPanel4.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 53, 429, 87));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 11, 510, 160));

        jPanel5.setLayout(new java.awt.GridLayout(1, 0));
        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 397, -1, 8));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("SALA DE VACUNACIÓN");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(412, 13, -1, -1));

        jLabel20.setText("Puesto 1");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 33, -1, -1));

        jLabel21.setText("Puesto 2");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 33, -1, -1));

        jLabel22.setText("Puesto 3");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 33, -1, -1));

        jLabel23.setText("Puesto 4");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(412, 33, -1, -1));

        jLabel24.setText("Puesto 5");
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(576, 33, -1, -1));

        jLabel25.setText("Puesto 6");
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 103, -1, -1));

        jLabel26.setText("Puesto 7");
        jPanel3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 103, -1, -1));

        jLabel27.setText("Puesto 8");
        jPanel3.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 103, -1, -1));

        jLabel28.setText("Puesto 9");
        jPanel3.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(412, 103, -1, -1));

        jLabel29.setText("Puesto 10");
        jPanel3.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(576, 103, -1, -1));

        jLabel30.setText("Auxiliar");
        jPanel3.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 33, -1, -1));

        jLabel31.setText("Vacunas Disponibles");
        jPanel3.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 103, -1, -1));

        jTextField14.setText("jTextField14");
        jTextField14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField14ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 123, 75, -1));

        jTextField15.setText("jTextField15");
        jPanel3.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(412, 123, 75, -1));

        jButton11.setText("jButton1");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 79, 73, -1));

        jButton12.setText("jButton2");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 79, 73, -1));

        jButton13.setText("jButton3");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 79, 73, -1));

        jButton14.setText("jButton4");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(412, 79, 73, -1));

        jButton15.setText("jButton5");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(576, 79, 73, -1));

        jButton16.setText("jButton6");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 149, 73, -1));

        jButton17.setText("jButton7");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 149, 73, -1));

        jButton18.setText("jButton8");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 149, -1, -1));

        jButton19.setText("jButton9");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(412, 149, -1, -1));

        jButton20.setText("jButton10");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 140, -1, -1));

        jTextField5.setText("jTextField5");
        jPanel3.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 75, -1));

        jTextField6.setText("jTextField6");
        jPanel3.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 75, -1));

        jTextField7.setText("jTextField7");
        jPanel3.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 75, -1));

        jTextField8.setText("jTextField8");
        jPanel3.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, 75, -1));

        jTextField9.setText("jTextField9");
        jPanel3.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, 75, -1));

        jTextField10.setText("jTextField10");
        jPanel3.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 50, 83, -1));

        jTextField11.setText("jTextField11");
        jPanel3.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 120, -1, -1));

        jTextField12.setText("jTextField12");
        jPanel3.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 75, -1));

        jTextField13.setText("jTextField13");
        jPanel3.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 75, -1));

        jTextField16.setText("jTextField16");
        jPanel3.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 120, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 940, 190));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        try{
            Socket soc = new Socket("localhost", 7777);
            ObjectOutputStream oos = new ObjectOutputStream(soc.getOutputStream());
            oos.flush();
            oos.writeObject(51);
        }catch(Exception e){}
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        try{
            Socket soc = new Socket("localhost", 7777);
            ObjectOutputStream oos = new ObjectOutputStream(soc.getOutputStream());
            oos.flush();
            oos.writeObject(52);
        }catch(Exception e){}
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        try{
            Socket soc = new Socket("localhost", 7777);
            ObjectOutputStream oos = new ObjectOutputStream(soc.getOutputStream());
            oos.flush();
            oos.writeObject(53);
        }catch(Exception e){}
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        try{
            Socket soc = new Socket("localhost", 7777);
            ObjectOutputStream oos = new ObjectOutputStream(soc.getOutputStream());
            oos.flush();
            oos.writeObject(54);
        }catch(Exception e){}
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        try{
            Socket soc = new Socket("localhost", 7777);
            ObjectOutputStream oos = new ObjectOutputStream(soc.getOutputStream());
            oos.flush();
            oos.writeObject(55);
        }catch(Exception e){}
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        try{
            Socket soc = new Socket("localhost", 7777);
            ObjectOutputStream oos = new ObjectOutputStream(soc.getOutputStream());
            oos.flush();
            oos.writeObject(56);
        }catch(Exception e){}
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        try{
            Socket soc = new Socket("localhost", 7777);
            ObjectOutputStream oos = new ObjectOutputStream(soc.getOutputStream());
            oos.flush();
            oos.writeObject(57);
        }catch(Exception e){}
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        try{
            Socket soc = new Socket("localhost", 7777);
            ObjectOutputStream oos = new ObjectOutputStream(soc.getOutputStream());
            oos.flush();
            oos.writeObject(58);
        }catch(Exception e){}
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        try{
            Socket soc = new Socket("localhost", 7777);
            ObjectOutputStream oos = new ObjectOutputStream(soc.getOutputStream());
            oos.flush();
            oos.writeObject(59);
        }catch(Exception e){}
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        try{
            Socket soc = new Socket("localhost", 7777);
            ObjectOutputStream oos = new ObjectOutputStream(soc.getOutputStream());
            oos.flush();
            oos.writeObject(60);
        }catch(Exception e){}
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField14ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField27ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField27ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextField27ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField23ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField23ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextField23ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazCliente.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazCliente.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazCliente.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazCliente.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazCliente().setVisible(true);

                

            }
        });
        
        try {

                    
                    while(true) {
                        
                        try {
                            Thread.sleep(1000);
                        } catch (Exception e) {
                        }
                        Socket s = new Socket("localhost", 7777);
                        ObjectOutputStream oos = new ObjectOutputStream(s.getOutputStream());
                        oos.flush();
                        oos.writeObject(1);
                        ObjectInputStream ois = new ObjectInputStream(s.getInputStream());
                        ArrayList<String> obj = (ArrayList<String>) ois.readObject();
                        for (int i = 0; i < 36; i++) {
                            tf.get(i).setText(obj.get(i));
                        }
                        
                    }

                } catch (Exception e) {
                    e.printStackTrace();
                }
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel10() {
        return jLabel10;
    }

    public void setjLabel10(JLabel jLabel10) {
        this.jLabel10 = jLabel10;
    }

    public JLabel getjLabel11() {
        return jLabel11;
    }

    public void setjLabel11(JLabel jLabel11) {
        this.jLabel11 = jLabel11;
    }

    public JLabel getjLabel12() {
        return jLabel12;
    }

    public void setjLabel12(JLabel jLabel12) {
        this.jLabel12 = jLabel12;
    }

    public JLabel getjLabel13() {
        return jLabel13;
    }

    public void setjLabel13(JLabel jLabel13) {
        this.jLabel13 = jLabel13;
    }

    public JLabel getjLabel14() {
        return jLabel14;
    }

    public void setjLabel14(JLabel jLabel14) {
        this.jLabel14 = jLabel14;
    }

    public JLabel getjLabel15() {
        return jLabel15;
    }

    public void setjLabel15(JLabel jLabel15) {
        this.jLabel15 = jLabel15;
    }

    public JLabel getjLabel16() {
        return jLabel16;
    }

    public void setjLabel16(JLabel jLabel16) {
        this.jLabel16 = jLabel16;
    }

    public JLabel getjLabel17() {
        return jLabel17;
    }

    public void setjLabel17(JLabel jLabel17) {
        this.jLabel17 = jLabel17;
    }

   

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel20() {
        return jLabel20;
    }

    public void setjLabel20(JLabel jLabel20) {
        this.jLabel20 = jLabel20;
    }

    public JLabel getjLabel21() {
        return jLabel21;
    }

    public void setjLabel21(JLabel jLabel21) {
        this.jLabel21 = jLabel21;
    }

    public JLabel getjLabel22() {
        return jLabel22;
    }

    public void setjLabel22(JLabel jLabel22) {
        this.jLabel22 = jLabel22;
    }

    public JLabel getjLabel23() {
        return jLabel23;
    }

    public void setjLabel23(JLabel jLabel23) {
        this.jLabel23 = jLabel23;
    }

    public JLabel getjLabel24() {
        return jLabel24;
    }

    public void setjLabel24(JLabel jLabel24) {
        this.jLabel24 = jLabel24;
    }

    public JLabel getjLabel25() {
        return jLabel25;
    }

    public void setjLabel25(JLabel jLabel25) {
        this.jLabel25 = jLabel25;
    }

    public JLabel getjLabel26() {
        return jLabel26;
    }

    public void setjLabel26(JLabel jLabel26) {
        this.jLabel26 = jLabel26;
    }

    public JLabel getjLabel27() {
        return jLabel27;
    }

    public void setjLabel27(JLabel jLabel27) {
        this.jLabel27 = jLabel27;
    }

    public JLabel getjLabel28() {
        return jLabel28;
    }

    public void setjLabel28(JLabel jLabel28) {
        this.jLabel28 = jLabel28;
    }

    public JLabel getjLabel29() {
        return jLabel29;
    }

    public void setjLabel29(JLabel jLabel29) {
        this.jLabel29 = jLabel29;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JLabel getjLabel30() {
        return jLabel30;
    }

    public void setjLabel30(JLabel jLabel30) {
        this.jLabel30 = jLabel30;
    }

    public JLabel getjLabel31() {
        return jLabel31;
    }

    public void setjLabel31(JLabel jLabel31) {
        this.jLabel31 = jLabel31;
    }

    public JLabel getjLabel32() {
        return jLabel32;
    }

    public void setjLabel32(JLabel jLabel32) {
        this.jLabel32 = jLabel32;
    }

    public JLabel getjLabel33() {
        return jLabel33;
    }

    public void setjLabel33(JLabel jLabel33) {
        this.jLabel33 = jLabel33;
    }

    public JLabel getjLabel34() {
        return jLabel34;
    }

    public void setjLabel34(JLabel jLabel34) {
        this.jLabel34 = jLabel34;
    }

    public JLabel getjLabel35() {
        return jLabel35;
    }

    public void setjLabel35(JLabel jLabel35) {
        this.jLabel35 = jLabel35;
    }

    public JLabel getjLabel36() {
        return jLabel36;
    }

    public void setjLabel36(JLabel jLabel36) {
        this.jLabel36 = jLabel36;
    }

    public JLabel getjLabel37() {
        return jLabel37;
    }

    public void setjLabel37(JLabel jLabel37) {
        this.jLabel37 = jLabel37;
    }

    public JLabel getjLabel38() {
        return jLabel38;
    }

    public void setjLabel38(JLabel jLabel38) {
        this.jLabel38 = jLabel38;
    }

    public JLabel getjLabel39() {
        return jLabel39;
    }

    public void setjLabel39(JLabel jLabel39) {
        this.jLabel39 = jLabel39;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public void setjLabel5(JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }

    public JLabel getjLabel6() {
        return jLabel6;
    }

    public void setjLabel6(JLabel jLabel6) {
        this.jLabel6 = jLabel6;
    }

    public JLabel getjLabel7() {
        return jLabel7;
    }

    public void setjLabel7(JLabel jLabel7) {
        this.jLabel7 = jLabel7;
    }

    public JLabel getjLabel8() {
        return jLabel8;
    }

    public void setjLabel8(JLabel jLabel8) {
        this.jLabel8 = jLabel8;
    }

    public JLabel getjLabel9() {
        return jLabel9;
    }

    public void setjLabel9(JLabel jLabel9) {
        this.jLabel9 = jLabel9;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JPanel getjPanel2() {
        return jPanel2;
    }

    public void setjPanel2(JPanel jPanel2) {
        this.jPanel2 = jPanel2;
    }

    public JPanel getjPanel3() {
        return jPanel3;
    }

    public void setjPanel3(JPanel jPanel3) {
        this.jPanel3 = jPanel3;
    }

    public JPanel getjPanel4() {
        return jPanel4;
    }

    public void setjPanel4(JPanel jPanel4) {
        this.jPanel4 = jPanel4;
    }

    public JSeparator getjSeparator1() {
        return jSeparator1;
    }

    public void setjSeparator1(JSeparator jSeparator1) {
        this.jSeparator1 = jSeparator1;
    }

    public JTextField getjTextField1() {
        return jTextField1;
    }

    public void setjTextField1(JTextField jTextField1) {
        this.jTextField1 = jTextField1;
    }

    public JTextField getjTextField10() {
        return jTextField10;
    }

    public void setjTextField10(JTextField jTextField10) {
        this.jTextField10 = jTextField10;
    }

    public JTextField getjTextField11() {
        return jTextField11;
    }

    public void setjTextField11(JTextField jTextField11) {
        this.jTextField11 = jTextField11;
    }

    public JTextField getjTextField12() {
        return jTextField12;
    }

    public void setjTextField12(JTextField jTextField12) {
        this.jTextField12 = jTextField12;
    }

    public JTextField getjTextField13() {
        return jTextField13;
    }

    public void setjTextField13(JTextField jTextField13) {
        this.jTextField13 = jTextField13;
    }

    public JTextField getjTextField14() {
        return jTextField14;
    }

    public void setjTextField14(JTextField jTextField14) {
        this.jTextField14 = jTextField14;
    }

    public JTextField getjTextField15() {
        return jTextField15;
    }

    public void setjTextField15(JTextField jTextField15) {
        this.jTextField15 = jTextField15;
    }

    public JTextField getjTextField16() {
        return jTextField16;
    }

    public void setjTextField16(JTextField jTextField16) {
        this.jTextField16 = jTextField16;
    }

    public JTextField getjTextField17() {
        return jTextField17;
    }

    public void setjTextField17(JTextField jTextField17) {
        this.jTextField17 = jTextField17;
    }

    public JTextField getjTextField18() {
        return jTextField18;
    }

    public void setjTextField18(JTextField jTextField18) {
        this.jTextField18 = jTextField18;
    }

    public JTextField getjTextField19() {
        return jTextField19;
    }

    public void setjTextField19(JTextField jTextField19) {
        this.jTextField19 = jTextField19;
    }

    public JTextField getjTextField2() {
        return jTextField2;
    }

    public void setjTextField2(JTextField jTextField2) {
        this.jTextField2 = jTextField2;
    }

    public JTextField getjTextField20() {
        return jTextField20;
    }

    public void setjTextField20(JTextField jTextField20) {
        this.jTextField20 = jTextField20;
    }

    public JTextField getjTextField21() {
        return jTextField21;
    }

    public void setjTextField21(JTextField jTextField21) {
        this.jTextField21 = jTextField21;
    }

    public JTextField getjTextField22() {
        return jTextField22;
    }

    public void setjTextField22(JTextField jTextField22) {
        this.jTextField22 = jTextField22;
    }

    public JTextField getjTextField23() {
        return jTextField23;
    }

    public void setjTextField23(JTextField jTextField23) {
        this.jTextField23 = jTextField23;
    }

    public JTextField getjTextField24() {
        return jTextField24;
    }

    public void setjTextField24(JTextField jTextField24) {
        this.jTextField24 = jTextField24;
    }

    public JTextField getjTextField25() {
        return jTextField25;
    }

    public void setjTextField25(JTextField jTextField25) {
        this.jTextField25 = jTextField25;
    }

    public JTextField getjTextField26() {
        return jTextField26;
    }

    public void setjTextField26(JTextField jTextField26) {
        this.jTextField26 = jTextField26;
    }

    public JTextField getjTextField27() {
        return jTextField27;
    }

    public void setjTextField27(JTextField jTextField27) {
        this.jTextField27 = jTextField27;
    }

    public JTextField getjTextField28() {
        return jTextField28;
    }

    public void setjTextField28(JTextField jTextField28) {
        this.jTextField28 = jTextField28;
    }

    public JTextField getjTextField29() {
        return jTextField29;
    }

    public void setjTextField29(JTextField jTextField29) {
        this.jTextField29 = jTextField29;
    }

    public JTextField getjTextField3() {
        return jTextField3;
    }

    public void setjTextField3(JTextField jTextField3) {
        this.jTextField3 = jTextField3;
    }

    public JTextField getjTextField30() {
        return jTextField30;
    }

    public void setjTextField30(JTextField jTextField30) {
        this.jTextField30 = jTextField30;
    }

    public JTextField getjTextField31() {
        return jTextField31;
    }

    public void setjTextField31(JTextField jTextField31) {
        this.jTextField31 = jTextField31;
    }

    public JTextField getjTextField32() {
        return jTextField32;
    }

    public void setjTextField32(JTextField jTextField32) {
        this.jTextField32 = jTextField32;
    }

    public JTextField getjTextField33() {
        return jTextField33;
    }

    public void setjTextField33(JTextField jTextField33) {
        this.jTextField33 = jTextField33;
    }

    public JTextField getjTextField34() {
        return jTextField34;
    }

    public void setjTextField34(JTextField jTextField34) {
        this.jTextField34 = jTextField34;
    }

    public JTextField getjTextField35() {
        return jTextField35;
    }

    public void setjTextField35(JTextField jTextField35) {
        this.jTextField35 = jTextField35;
    }

    public JTextField getjTextField36() {
        return jTextField36;
    }

    public void setjTextField36(JTextField jTextField36) {
        this.jTextField36 = jTextField36;
    }

    public JTextField getjTextField4() {
        return jTextField4;
    }

    public void setjTextField4(JTextField jTextField4) {
        this.jTextField4 = jTextField4;
    }

    public JTextField getjTextField5() {
        return jTextField5;
    }

    public void setjTextField5(JTextField jTextField5) {
        this.jTextField5 = jTextField5;
    }

    public JTextField getjTextField6() {
        return jTextField6;
    }

    public void setjTextField6(JTextField jTextField6) {
        this.jTextField6 = jTextField6;
    }

    public JTextField getjTextField7() {
        return jTextField7;
    }

    public void setjTextField7(JTextField jTextField7) {
        this.jTextField7 = jTextField7;
    }

    public JTextField getjTextField8() {
        return jTextField8;
    }

    public void setjTextField8(JTextField jTextField8) {
        this.jTextField8 = jTextField8;
    }

    public JTextField getjTextField9() {
        return jTextField9;
    }

    public void setjTextField9(JTextField jTextField9) {
        this.jTextField9 = jTextField9;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField31;
    private javax.swing.JTextField jTextField32;
    private javax.swing.JTextField jTextField33;
    private javax.swing.JTextField jTextField34;
    private javax.swing.JTextField jTextField35;
    private javax.swing.JTextField jTextField36;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
